updates:
  - directory: "/"
    open-pull-requests-limit: 16
    package-ecosystem: "npm"
    schedule:
      interval: "daily"
    target-branch: npm-and-yarn
  - directory: "/"
    open-pull-requests-limit: 16
    package-ecosystem: "github-actions"
    schedule:
      interval: "daily"
    target-branch: devel
version: 2
